language: python
python: "3.8"
before_install:
  - chmod +x build.sh && ./build.sh
install:
  - pip install -r requirements.txt
script:
  - coverage run --source='.' manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)